import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import GlobalHeader from './components/global-header';

const font = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-sky-900 ${font.className}`}>
        <GlobalHeader />
        <div className="container mx-auto bg-white p-4 min-h-screen rounded-tl-xl rounded-tr-xl">
          {children}
        </div>
      </body>
    </html>
  )
}
